# Netlify configuration file

# Build settings
[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command
  command = "npm run build"
  # Functions directory
  functions = "netlify/functions"

# Redirects and rewrites
[[redirects]]
  # Redirect all API requests to the serverless function
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200